version: '3'

networks:
  Portfolio-api:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8088:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - Portfolio-api
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - Portfolio-api
  database:
    image: mongo
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nelwhix
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - Portfolio-api